name: Npm Publish
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm install

    - name: fabric custom build
      run: |
        npm i -g uglify-js
        mkdir dist
        node ./node_modules/fabric/build.js modules=interaction,animation,node

    - name: Webpack build
      run: npm run build

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
